export default function UseOptions() {
  const optionsMeses = [
    "janeiro",
    "fevereiro",
    "março",
    "abril",
    "maio",
    "junho",
    "julho",
    "agosto",
    "setembro",
    "outubro",
    "novembro",
    "dezembro",
  ];

  const optionsAnos = [
    "2023",
    "2024",
    "2025",
    "2026",
    "2027",
    "2028",
    "2029",
    "2030",
  ];

  const diasDaSemana = [
    "Domingo",
    "Segunda",
    "Terça",
    "Quarta",
    "Quinta",
    "Sexta",
    "Sábado",
  ];

  const categoriasReceita = [
    { id: 1, name: "Ajuste de Saldo" },
    { id: 2, name: "Investimentos" },
    { id: 3, name: "PLR" },
    { id: 4, name: "Prêmios" },
    { id: 5, name: "Presente" },
    { id: 6, name: "Reembolso" },
    { id: 7, name: "Salário" },
    { id: 8, name: "Saldo Anterior" },
    { id: 9, name: "Vendas" },
    { id: 10, name: "Outros" },
  ];

  const categoriasDespesa = [
    { id: 1, name: "Ajuste de Saldo" },
    { id: 2, name: "Alimentação" },
    { id: 3, name: "Assinaturas" },
    { id: 4, name: "Bares" },
    { id: 5, name: "Compras" },
    { id: 6, name: "Cuidados pessoais" },
    { id: 7, name: "Educação" },
    { id: 8, name: "Empréstimos" },
    { id: 9, name: "Lazer e hobbies" },
    { id: 10, name: "Loteria e Apostas" },
    { id: 11, name: "Mercado" },
    { id: 12, name: "Moradia" },
    { id: 13, name: "Outros" },
    { id: 14, name: "Pagamentos" },
    { id: 15, name: "Restaurantes" },
    { id: 16, name: "Roupas" },
    { id: 17, name: "Saúde" },
    { id: 18, name: "Terceiros" },
    { id: 19, name: "Trabalho" },
    { id: 20, name: "Transporte" },
    { id: 21, name: "Viagem" },
  ];

  const logos = [
    { file: "99Pay.png", name: "99Pay" },
    { file: "alelo.png", name: "Alelo" },
    { file: "azul.png", name: "Azul" },
    { file: "b3.png", name: "B3" },
    { file: "banrisul.png", name: "Banrisul" },
    { file: "bb.png", name: "Banco do Brasil" },
    { file: "bmg.png", name: "BMG" },
    { file: "bradesco.png", name: "Bradesco" },
    { file: "brb.png", name: "BRB" },
    { file: "bs2.png", name: "BS2" },
    { file: "c6bank.png", name: "C6" },
    { file: "caixa.png", name: "Caixa" },
    { file: "citibank.png", name: "Citibank" },
    { file: "cooperativa-cresol.png", name: "Cooperativa Cresol" },
    { file: "credicard-on.png", name: "Credicard On" },
    { file: "credicard-zero.png", name: "Credicard Zero" },
    { file: "credicard.png", name: "Credicard" },
    { file: "digio.png", name: "Digio" },
    { file: "diners.png", name: "Diners" },
    { file: "elo.png", name: "Elo" },
    { file: "infinitepay.png", name: "InfinitePay" },
    { file: "intermedium.png", name: "Inter" },
    { file: "interpj.png", name: "Inter PJ" },
    { file: "itau-ion.png", name: "Itaú Ion" },
    { file: "itau-uniclass.png", name: "Itaú Uniclass" },
    { file: "itau.png", name: "Itaú" },
    { file: "itaupersonnalite.png", name: "Itaú Personnalité" },
    { file: "iti.png", name: "Iti" },
    { file: "magalu-pay.png", name: "Magalu Pay" },
    { file: "mastercard.png", name: "Mastercard" },
    { file: "mercadobitcoin.png", name: "Mercado Bitcoin" },
    { file: "mercadopago.png", name: "Mercado Pago" },
    { file: "neon.png", name: "Neon" },
    { file: "next.png", name: "Next" },
    { file: "nu-invest.png", name: "Nu Invest" },
    { file: "nubank.png", name: "Nubank" },
    { file: "nuconta.png", name: "NuConta" },
    { file: "original.png", name: "Original" },
    { file: "pagbank.png", name: "PagBank" },
    { file: "pagseguro.png", name: "PagSeguro" },
    { file: "paypal.png", name: "PayPal" },
    { file: "petrobras.png", name: "Petrobras" },
    { file: "picpay.png", name: "PicPay" },
    { file: "recargapay.png", name: "RecargaPay" },
    { file: "renner.png", name: "Renner" },
    { file: "safra.png", name: "Safra" },
    { file: "samsung.png", name: "Samsung" },
    { file: "santander-private.png", name: "Santander Private" },
    { file: "santander.png", name: "Santander" },
    { file: "sofisadireto.png", name: "Sofisa Direto" },
    { file: "stone.png", name: "Stone" },
    { file: "uber.drive.png", name: "Uber Drive" },
    { file: "visa.png", name: "Visa" },
    { file: "vuon.png", name: "Vuon" },
    { file: "vr.png", name: "VR" },
    { file: "xp.png", name: "XP" },
  ];

  const bandeiras = [
    { file: "visa.svg", name: "Visa" },
    { file: "mastercard.svg", name: "Mastercard" },
    { file: "vuon.svg", name: "Vuoncard" },
  ];

  return {
    categoriasDespesa,
    categoriasReceita,
    optionsMeses,
    optionsAnos,
    diasDaSemana,
    logos,
    bandeiras,
  };
}
