import {
  Award,
  Beer,
  Bike,
  Briefcase,
  Car,
  CircleDollarSign,
  Coffee,
  CreditCard,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  History,
  Home,
  Newspaper,
  PiggyBank,
  Plane,
  RefreshCw,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Stars,
  TrendingUp,
  Trophy,
  Users,
  UtensilsCrossed,
  Wallet,
} from "lucide-react";

export default function UseOptions() {
  const categoriasReceita = [
    { id: 1, name: "ajuste de saldo", icon: History },
    { id: 2, name: "investimentos", icon: TrendingUp },
    { id: 3, name: "plr", icon: Award },
    { id: 4, name: "prêmios", icon: Trophy },
    { id: 5, name: "presente", icon: Gift },
    { id: 6, name: "reembolso", icon: RefreshCw },
    { id: 7, name: "salário", icon: Briefcase },
    { id: 8, name: "saldo anterior", icon: Wallet },
    { id: 9, name: "vendas", icon: ShoppingCart },
    { id: 10, name: "rendimentos", icon: PiggyBank },
    { id: 11, name: "outros", icon: CircleDollarSign },
  ];

  const categoriasDespesa = [
    { id: 1, name: "ajuste de saldo", icon: History },
    { id: 2, name: "alimentação", icon: UtensilsCrossed },
    { id: 3, name: "assinaturas", icon: Newspaper },
    { id: 4, name: "bares", icon: Beer },
    { id: 5, name: "beleza", icon: Scissors },
    { id: 6, name: "compras", icon: ShoppingBag },
    { id: 7, name: "cuidados pessoais", icon: Scissors },
    { id: 8, name: "delivery", icon: Bike },
    { id: 9, name: "educação", icon: GraduationCap },
    { id: 10, name: "empréstimos", icon: PiggyBank },
    { id: 11, name: "lazer e hobbies", icon: Gamepad2 },
    { id: 12, name: "loteria e apostas", icon: Stars },
    { id: 13, name: "mercado", icon: ShoppingCart },
    { id: 14, name: "moradia", icon: Home },
    { id: 15, name: "outros", icon: CircleDollarSign },
    { id: 16, name: "pagamentos", icon: CreditCard },
    { id: 17, name: "presentes", icon: Gift },
    { id: 18, name: "restaurantes", icon: Coffee },
    { id: 19, name: "roupas", icon: Shirt },
    { id: 20, name: "saúde", icon: Heart },
    { id: 21, name: "terceiros", icon: Users },
    { id: 22, name: "trabalho", icon: Briefcase },
    { id: 23, name: "transporte", icon: Car },
    { id: 24, name: "viagem", icon: Plane },
  ];

  const logos = [
    { file: "99Pay.png", name: "99Pay" },
    { file: "alelo.png", name: "Alelo" },
    { file: "azul.png", name: "Azul" },
    { file: "b3.png", name: "B3" },
    { file: "banrisul.png", name: "Banrisul" },
    { file: "bb.png", name: "Banco do Brasil" },
    { file: "bmg.png", name: "BMG" },
    { file: "bradesco.png", name: "Bradesco" },
    { file: "brb.png", name: "BRB" },
    { file: "bs2.png", name: "BS2" },
    { file: "c6bank.png", name: "C6" },
    { file: "caixa.png", name: "Caixa" },
    { file: "citibank.png", name: "Citibank" },
    { file: "cooperativa-cresol.png", name: "Cooperativa Cresol" },
    { file: "credicard-on.png", name: "Credicard On" },
    { file: "credicard-zero.png", name: "Credicard Zero" },
    { file: "credicard.png", name: "Credicard" },
    { file: "digio.png", name: "Digio" },
    { file: "diners.png", name: "Diners" },
    { file: "elo.png", name: "Elo" },
    { file: "infinitepay.png", name: "InfinitePay" },
    { file: "intermedium.png", name: "Inter" },
    { file: "interpj.png", name: "Inter PJ" },
    { file: "itau-ion.png", name: "Itaú Ion" },
    { file: "itau-uniclass.png", name: "Itaú Uniclass" },
    { file: "itau.png", name: "Itaú" },
    { file: "itaupersonnalite.png", name: "Itaú Personnalité" },
    { file: "iti.png", name: "Iti" },
    { file: "magalu-pay.png", name: "Magalu Pay" },
    { file: "mastercard.png", name: "Mastercard" },
    { file: "mercadobitcoin.png", name: "Mercado Bitcoin" },
    { file: "mercadopago.png", name: "Mercado Pago" },
    { file: "mercadopagocartao.png", name: "Cartão Mercado Pago" },
    { file: "neon.png", name: "Neon" },
    { file: "next.png", name: "Next" },
    { file: "nu-invest.png", name: "Nu Invest" },
    { file: "nubank.png", name: "Nubank" },
    { file: "nuconta.png", name: "NuConta" },
    { file: "original.png", name: "Original" },
    { file: "pagbank.png", name: "PagBank" },
    { file: "pagseguro.png", name: "PagSeguro" },
    { file: "paypal.png", name: "PayPal" },
    { file: "petrobras.png", name: "Petrobras" },
    { file: "picpay.png", name: "PicPay" },
    { file: "recargapay.png", name: "RecargaPay" },
    { file: "renner.png", name: "Renner" },
    { file: "safra.png", name: "Safra" },
    { file: "samsung.png", name: "Samsung" },
    { file: "santander-private.png", name: "Santander Private" },
    { file: "santander.png", name: "Santander" },
    { file: "sofisadireto.png", name: "Sofisa Direto" },
    { file: "stone.png", name: "Stone" },
    { file: "uber.drive.png", name: "Uber Drive" },
    { file: "visa.png", name: "Visa" },
    { file: "vuon.png", name: "Vuon" },
    { file: "vr.png", name: "VR" },
    { file: "xp.png", name: "XP" },
  ];

  const bandeiras = [
    { file: "visa.svg", name: "Visa" },
    { file: "mastercard.svg", name: "Mastercard" },
    { file: "vuon.svg", name: "Vuoncard" },
  ];

  return {
    categoriasDespesa,
    categoriasReceita,
    logos,
    bandeiras,
  };
}
