-- Extensions
CREATE EXTENSION IF NOT EXISTS pg_graphql WITH SCHEMA graphql VERSION '1.5.11';
CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions VERSION '0.14.0';
CREATE EXTENSION IF NOT EXISTS pg_stat_statements WITH SCHEMA extensions VERSION '1.10';
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions VERSION '1.3';
-- CREATE EXTENSION IF NOT EXISTS pgsodium WITH SCHEMA pgsodium VERSION '3.1.8';
CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog VERSION '1.0';
CREATE EXTENSION IF NOT EXISTS supabase_vault WITH SCHEMA vault VERSION '0.3.1';
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA extensions VERSION '1.1';
